alpha: 1
dt: 0.2
N: 10
Lbase: 0.27
v_max: 1.5
v_lin_max: 0.7
v_ang_max: 6.0
verbose: False
n_states: 3
n_controls: 2
mu: 1.0
nu: 0.4
eps: 1e-6
gain_ctrack_error_x: 20
gain_ctrack_error_y: 20
gain_ctrack_error_theta: 1
terminal_cost_multiplier_x: 100
terminal_cost_multiplier_y: 100
terminal_cost_multiplier_theta: 10
gain_control_effort_linear: 10
gain_control_effort_angular: 1
use_delay: False